# Generated by Django 5.0.7 on 2026-02-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_projects_classification_projects_collaborators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
