# Generated by Django 5.0.7 on 2026-02-25 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_projects_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='conversations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='application.projects')),
                ('sender_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.student')),
                ('sender_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.supervisor')),
            ],
        ),
    ]
